# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ariticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('abstract', models.CharField(help_text='必选,请勿空白', max_length=50, verbose_name='摘要')),
                ('body', models.TextField(verbose_name='正文')),
                ('title_pic', models.ImageField(upload_to='pic_folder/', verbose_name='题图')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('thumbs', models.PositiveIntegerField(default=0, verbose_name='点赞量')),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=20, verbose_name='昵称')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20, verbose_name='类型')),
            ],
        ),
        migrations.AddField(
            model_name='ariticle',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Author', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='ariticle',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.Category', verbose_name='分类'),
        ),
    ]
