# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20160905_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(help_text='必选,请勿空白', max_length=150, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic_folder/', verbose_name='题图'),
        ),
    ]
